alias ls='ls --color=auto'
alias dir='ls -a'
alias cl='clear'
alias cs='clear'
alias cls='clear'
alias co='code'
alias sc='source'
alias vi='nvim'
alias v='nvim'
alias vim='nvim'
alias rf='rm -rf'
alias t='touch'
alias mkd='mkdir'
alias hs='history'

alias nis='npm install'
alias ns='npm start'
alias nrd='npm run dev'
alias nt='npm run test'

alias gi='git init'
alias gs='git status'
alias ga='git add'
alias gl='git log'
alias gif='git diff'
alias gpl='git pull'
alias gpu='git push'
alias gch='git checkout'
alias gr='git remote -v'
alias gra='git remote add origin'

alias bi='brew install'
alias bu='brew uninstall'
alias bl='brew list'

alias rn='cargo run'

